version: '3.5' 

services: 

    postgres:
      image: postgres
      restart: unless-stopped
      volumes:
        - ./postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: database

    backend: 
      image: backend-example-docker
      ports:
        - 8000:8000
      environment:
        - REDIS=redis
        - DB_USERNAME=user
        - DB_PASSWORD=password
        - DB_NAME=database
        - DB_HOST=postgres
      depends_on:
        - postgres

    redis:
      image: redis
      ports:
        - 6379:6379
      volumes:
        - ./redis_data:/data

    nginx: 
      image: jwilder/nginx-proxy 
      volumes: 
        - /var/run/docker.sock:/tmp/docker.sock:ro 
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports: 
        - 80:80 
      depends_on:
      - frontend
      - backend

    frontend:
      image: frontend-example-docker
      ports:
        - 5000:5000
      depends_on:
        - postgres
        - backend