version: '3.5' 

services: 

    backend: 
      image: backend-example-docker
      ports:
        - 8000:8000
      environment:
        - REDIS=redis

    redis:
      image: redis
      ports:
        - 6379:6379

    #For testing purposes:
    frontend:
      image: frontend-example-docker
      ports:
        - 5000:5000