name: CI

env:
  SHA12: ${GITHUB_SHA::12}


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Testing stuff
      run: |
        echo Full SHA1 = ${{github.sha}}
        echo Short SHA12 = ${{env.SHA12}}-customIndentifier
        echo ${{github.GITHUB_REPOSITORY}}
        echo ${{NODE_ENV}}
