name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      env:
        SHA12: ${GITHUB_SHA::12}
    - name: Testing stuff
      run: echo Full SHA1 = ${{env.SHA12}}
      

